#!/bin/bash
#SBATCH --time=24:00:00   # walltime
#SBATCH --ntasks=2   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --gres=gpu:1
#SBATCH --mem-per-cpu=16G   # memory per CPU core
#SBATCH --mail-user=rbao@caltech.edu   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --error=errors/train.err 
#SBATCH --output=outputs/train.out
#Submit this script with: sbatch thefilename

#Activate conda env
source activate tensor
nvidia-smi
echo "Environment activated, running file...."

cd ../../
cd task1
cd models
cd one_stream

# python lightning_train.py
python lightning_train.py --rnn_model "convLSTM"
# python lightning_train.py --arch "resnet18" --rnn_model "LSTM" 
# python lightning_train.py --arch "resnet18" --rnn_model "convLSTM" 

# cd ../
# cd two_stream
# python lightning_train.py
# python lightning_train.py --rnn_model "convLSTM"
# python lightning_train.py --arch "resnet18" --rnn_model "LSTM" 
# python lightning_train.py --arch "resnet18" --rnn_model "convLSTM" 

#python lightning_train.py --datadir /central/groups/tensorlab/rbao/robosurgery/balint_data/classification_data --include_classes "AB_BC"

