accum_batches: 8
arch: alexnet
auto_lr: false
batch_size: 1
datadir: /mnt/md1/richard_bao/balint_data/label_classification_data
epochs: 50
fc_size: 64
flow_method: flownet
gpu: 3
hidden_size: 128
idx_test: []
idx_train: []
include_classes:
- positiveC
- negativeC
kinematics_features:
- Tool_Camera_X
- Tool_Camera_Y
- Tool_Camera_Z
- Tool_Camera_Yaw
- Tool_Camera_Pitch
- Tool_Camera_Roll
- Tool_Left_X
- Tool_Left_Y
- Tool_Left_Z
- Tool_Left_Yaw
- Tool_Left_Pitch
- Tool_Left_Roll
- Tool_Left_Jaw_Opening_Angle
- Tool_Right_X
- Tool_Right_Y
- Tool_Right_Z
- Tool_Right_Yaw
- Tool_Right_Pitch
- Tool_Right_Roll
- Tool_Right_Jaw_Opening_Angle
kinematicsdir: /mnt/md1/richard_bao/balint_data/kinematics/demonstrations
kweight: 1.0
loadchk: ''
loader_nframes: 200
loader_stride: 1
logging_dir: lightning_logs
lr: 0.0001
lr_lambdas: 0.9
masked: ''
number_workers: 3
overfit: 0
random_crop: false
rnn_layers: 2
rnn_model: convLSTM
seed: 0
train_proportion: 0.8
trainable_base: false
upsample: false
use_pretrained: true
weight_decay: 1.0e-05
