accum_batches: 3
auto_lr: false
batch_size: 1
checkpoint_path: /home/richard_bao/robosurgery/checkpoints/task1/two_stream/AC_CE_EF_FG/_ckpt_epoch_46.ckpt
datadir: /mnt/md1/richard_bao/balint_data/label_classification_data
epochs: 60
filenames: []
flow_method: flownet
gpu: 0
hparams_path: /home/richard_bao/robosurgery/deepStitch/task1/models/two_stream/test/hparams.yaml
idx_test: []
idx_train: []
include_classes:
- positive
- negative
input_file: /home/richard_bao/robosurgery/deepStitch/task1/models/two_stream/test/test1.mp4
loadchk: ''
loader_nframes: 140
loader_stride: 2
logging_dir: lightning_logs
lr: 0.0001
lr_lambdas: 0.9
masked: ''
number_workers: 0
overfit: 0
random_crop: false
seed: 0
train_proportion: 0.8
use_pretrained: true
weight_decay: 0.01
