#!/bin/bash
#SBATCH --time=24:00:00   # walltime
#SBATCH --ntasks=1   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --gres=gpu:1
#SBATCH --mail-user=rbao@caltech.edu   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL

#Submit this script with: sbatch thefilename

#Activate conda env
conda activate tensor
nvidia-smi
echo "Environment activated, running file...."

srun ./central/groups/tensorlab/rbao/deepStitch/preprocessing/optical_flow/generate_flows.sh
