accum_batches: 1
arch: alexnet
auto_lr: false
datadir: /central/groups/tensorlab/rbao/robosurgery/balint_data/classification_data
epochs: 60
fc_size: 32
flow_method: flownet
gpu: 0
hidden_size: 16
idx_test: []
idx_train: []
include_classes:
- positive
- negative
loadchk: ''
loader_nframes: 140
loader_stride: 2
logging_dir: lightning_logs
lr: 0.0001
lr_lambdas: 0.9
overfit: 0
random_crop: false
rnn_layers: 2
rnn_model: LSTM
seed: 0
train_proportion: 0.8
trainable_base: false
use_pretrained: true
weight_decay: 0.01
