accum_batches: 8
arch: alexnet
auto_lr: false
batch_size: 1
datadir: /mnt/md1/richard_bao/balint_data/label_classification_data
epochs: 50
fc_size: 64
filenames: []
flow_method: flownet
gpu: 3
hidden_size: 128
idx_test: []
idx_train: []
include_classes:
- positiveB
- negativeB
loadchk: ''
loader_nframes: 140
loader_stride: 2
logging_dir: lightning_logs
lr: 0.0001
lr_lambdas: 0.9
masked: ''
number_workers: 3
overfit: 0
random_crop: false
rnn_layers: 2
rnn_model: convLSTM
seed: 0
train_proportion: 0.8
trainable_base: false
upsample: false
use_pretrained: true
weight_decay: 1.0e-05
